export const ADD_OPEN_PROJECT = 'ADD_OPEN_PROJECT'
export const REMOVE_OPEN_PROJECT = 'REMOVE_OPEN_PROJECT'

export const TIC_TAC_TOE_OPEN_MODAL = 'TIC_TAC_TOE_OPEN_MODAL'
export const TIC_TAC_TOE_CLOSE_MODAL = 'TIC_TAC_TOE_CLOSE_MODAL'
export const TIC_TAC_SET_USER_CHARACTER = 'TIC_TAC_SET_USER_CHARACTER'
export const HIDE_TIC_TAC_START_BUTTON = 'HIDE_TIC_TAC_START_BUTTON'
export const UPDATE_TIC_TAC_BOARD = 'UPDATE_TIC_TAC_BOARD'
export const RESET_TIC_TAC = 'RESET_TIC_TAC'
